### ISSUE TITLE
Alternative instantiation for Services

### ISSUE THREAD

**Issue by wimvelzeboer** [apex-enterprise-patterns/fflib-apex-common-samplecode#32]
Hi @ImJohnMDaniel 

In these examples I see that thee are a number of different ways to create new instances for the several classes.
For domains there is a static method `newInstance` on the implementation class `Accounts`  
(e.g. `static IAccounts newInstance(Set<Id> recordIdSet)`).
The service classes have their own separate class (e.g. `OpportunitiesService`) with a static version of all the method signatures of its Interface.

There are also many developers I work with, who find this a bit cumbersome, a too big overhead and duplication of method signatures.

Would it be an idea to do something similar as we do with the domain?
How would you feel about calling service methods not via:
`OpportunitiesService.applyDiscounts(ids, 10);`
but via a lazy loading static property on the domain:
`Opportunities.Service.applyDiscounts(ids, 10);`
or exactly the same as the domain:
`OpportunitiesService.newInstance().applyDiscounts(Ids, 10);`

Have you had any discussions about this approach in the past? 
It would be nice if we can avoid that class with statics..

CC: @daveespo, @afawcett, @stohn777

**Comment by joeythomaschaske** [comment]
Doesn't this defeat the purpose of the dependency injection then? The business code shouldn't interact with the concrete implementation classes directly to get a new instance, it should go through the Application class to get its dependency  where it can be injected

**Comment by stohn777** [comment]
Per established architectural patterns [1][2], a Service represents a collection of related functions that, as a whole, work together to provide a conceptual feature or otherwise boundary around a logical group of functions.  A Service will likely encapsulate multiple Domains, Selectors and application logic to achieve the feature.  Therefore directly relating a Service to a Domain, I see, is an anti-pattern.

[1] https://andyinthecloud.com/2013/02/11/apex-enterprise-patterns-service-layer/
[2] https://martinfowler.com/eaaCatalog/serviceLayer.html

**Comment by daveespo** [comment]
As this is a Discussion more than an Issue, I'm closing it -- if you'd like to continue the conversation, please open a new Discussion
